default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: today_news_development

test:
  <<: *default
  database: today_news_test

production:
  <<: *default
  database: today_news_production
  password: <%= ENV['today_news_DATABASE_PASSWORD'] %>
