default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_scraper_development

test:
  <<: *default
  database: news_scraper_test

production:
  <<: *default
  database: news_scraper_production
  username: news_scraper
  password: <%= ENV['NEWS_SCRAPER_DATABASE_PASSWORD'] %>
